; generated by PrusaSlicer 2.7.2 on 2026-09-23 at 14:13:19 UTC
M82 ; absolute extrusion
G92 E0
;LAYER_CHANGE
;Z:0.3
G1 E-1 F2400
G1 E0 F2400
G1 X10 Y10 E5
G1 X20 Y10 E10
;LAYER_CHANGE
;Z:0.5
G92 E0
G1 X10 Y20 E4 ; comment
M83
G1 X0 Y0 E1.5
G1 E-0.5
;LAYER_CHANGE
;Z:0.7
G1 X5 Y5 E2
; filament used [mm] = 17.00
; filament used [cm3] = 0.04
; total filament used [g] = 0.05
; total filament cost = 0.00
; estimated printing time (normal mode) = 1h 2m 3s
; estimated first layer printing time (normal mode) = 46s

; prusaslicer_config = begin
; filament_cost = 0
; filament_density = 1.24
; layer_height = 0.2
; first_layer_height = 0.3
; prusaslicer_config = end
