from pathlib import Path
import pytest

from vegeta.mellonia import Orientation, PrintSettings, parse_duration, read_gcode, read_ini, slice_stl
from vegeta.mellonia.examples import GENERIC_PLA_0_2MM

DATA = Path(__file__).parent / "data"


def test_required_keys_are_enforced():
    with pytest.raises(ValueError, match="layer_height"):
        GENERIC_PLA_0_2MM.replace().__class__(printer=GENERIC_PLA_0_2MM.printer, filament=GENERIC_PLA_0_2MM.filament,
                                              print={k: v for k, v in GENERIC_PLA_0_2MM.print.items() if k != "layer_height"})
    with pytest.raises(ValueError, match="more than one section"):
        GENERIC_PLA_0_2MM.replace(filament={"layer_height": 0.1})
    with pytest.raises(ValueError, match="unknown section"):
        GENERIC_PLA_0_2MM.replace(slicer={"x": 1})


def test_write_and_read_ini_round_trip(tmp_path):
    paths = GENERIC_PLA_0_2MM.write(tmp_path)
    assert [p.name for p in paths] == ["printer.ini", "filament.ini", "print.ini"]
    back = PrintSettings.from_ini(*paths)
    assert back.print["fill_density"] == "20%" and back.printer["nozzle_diameter"] == "0.4"
    assert read_ini(paths[2])["layer_height"] == "0.2"


def test_orientation_cli_args():
    assert Orientation().cli_args() == []
    assert Orientation(90, 0, 45).cli_args() == ["--rotate-x", "90", "--rotate", "45"]


@pytest.mark.parametrize("text, secs", [("1h 2m 3s", 3723), ("46s", 46), ("1d 0h 1m 0s", 86460), ("", None), ("soon", None)])
def test_parse_duration(text, secs):
    assert parse_duration(text) == secs


def test_read_gcode_fixture():
    info = read_gcode(DATA / "tiny.gcode")
    assert info.layer_count == 3 and list(info.layer_z) == [0.3, 0.5, 0.7]
    # layer 1: -1 +1 +5 +5 = 10 ; layer 2: G92 reset, +4 (abs) then relative +1.5 -0.5 = 5 ; layer 3: +2
    assert list(info.layer_extrusion_mm) == pytest.approx([10, 5, 2])
    m = info.metrics()
    assert m["estimated_time_s"] == 3723 and m["first_layer_time_s"] == 46
    assert m["filament_used_mm"] == 17 and m["filament_used_g"] == pytest.approx(0.05)
    assert m["filament_cost"] is None  # cost not configured -> not reported
    assert m["max_z"] == pytest.approx(0.7) and m["first_layer_height"] == pytest.approx(0.3)
    assert info.generator.startswith("generated by PrusaSlicer")


def test_missing_executable_and_stl_are_failed_results(tmp_path, cube_stl):
    r = slice_stl(cube_stl, GENERIC_PLA_0_2MM, Orientation(), tmp_path / "a", executable="no-such-slicer")
    assert r.status == "failed" and "not found" in r.messages[0] and r.execution[0].returncode is None
    r = slice_stl(tmp_path / "missing.stl", GENERIC_PLA_0_2MM, Orientation(), tmp_path / "b")
    assert not r.ok and "STL not found" in r.messages[0]
    with pytest.raises(ValueError, match="Orientation"):
        slice_stl(cube_stl, GENERIC_PLA_0_2MM, None, tmp_path / "c")
