"""Read PrusaSlicer G-code: summary comments, effective configuration and per-layer data."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

_TIME = re.compile(r"(?:(\d+)d)?\s*(?:(\d+)h)?\s*(?:(\d+)m)?\s*(?:(\d+)s)?")


def parse_duration(text: str) -> float | None:
    """'1d 2h 3m 4s' -> seconds."""
    text = text.strip()
    m = _TIME.fullmatch(text)
    if not text or not m or not any(m.groups()):
        return None
    d, h, mi, s = (int(g) if g else 0 for g in m.groups())
    return float(((d * 24 + h) * 60 + mi) * 60 + s)


@dataclass
class GcodeInfo:
    path: Path
    comments: dict[str, str]             # '; key = value' summary lines outside the config block
    config: dict[str, str]               # effective PrusaSlicer configuration
    layer_z: np.ndarray                  # Z of each layer (from ;Z: after ;LAYER_CHANGE)
    layer_extrusion_mm: np.ndarray       # net filament length extruded per layer
    generator: str | None = None
    messages: list[str] = field(default_factory=list)

    @property
    def layer_count(self) -> int:
        return int(len(self.layer_z))

    def metrics(self) -> dict:
        c = self.comments
        m: dict = {}
        m["estimated_time_s"] = parse_duration(c.get("estimated printing time (normal mode)", ""))
        m["estimated_time_silent_s"] = parse_duration(c.get("estimated printing time (silent mode)", ""))
        m["estimated_time"] = c.get("estimated printing time (normal mode)")
        m["first_layer_time_s"] = parse_duration(c.get("estimated first layer printing time (normal mode)", ""))
        m["filament_used_mm"] = _num(c.get("filament used [mm]"))
        m["filament_used_cm3"] = _num(c.get("filament used [cm3]"))
        density = _num(self.config.get("filament_density"))
        cost = _num(self.config.get("filament_cost"))
        grams = _num(c.get("total filament used [g]", c.get("filament used [g]")))
        m["filament_used_g"] = grams if density else None
        m["filament_cost"] = _num(c.get("total filament cost", c.get("filament cost"))) if cost else None
        m["layer_count"] = self.layer_count
        m["max_z"] = float(self.layer_z.max()) if self.layer_count else None
        m["layer_height"] = _num(self.config.get("layer_height"))
        m["first_layer_height"] = _num(self.config.get("first_layer_height"))
        return m


def _num(v) -> float | None:
    if v is None:
        return None
    try:
        return float(str(v).split(",")[0].rstrip("%"))
    except ValueError:
        return None


def read_gcode(path: str | Path) -> GcodeInfo:
    path = Path(path)
    comments: dict[str, str] = {}
    config: dict[str, str] = {}
    z: list[float] = []
    per_layer: list[float] = []
    in_config = False
    pending_layer = False
    relative = False
    e_pos = 0.0
    current = 0.0
    generator = None
    with path.open("r", errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not line:
                continue
            if line.startswith(";"):
                if line.startswith("; prusaslicer_config = begin"):
                    in_config = True
                elif line.startswith("; prusaslicer_config = end"):
                    in_config = False
                elif line == ";LAYER_CHANGE":
                    pending_layer = True
                elif line.startswith(";Z:") and pending_layer:
                    if z:
                        per_layer.append(current)
                    z.append(float(line[3:]))
                    current = 0.0
                    pending_layer = False
                elif line.startswith("; generated by"):
                    generator = line[2:]
                elif line.startswith("; ") and " = " in line:
                    k, v = line[2:].split(" = ", 1)
                    (config if in_config else comments)[k.strip()] = v.strip()
                continue
            code = line.split(";", 1)[0].split()
            if not code:
                continue
            cmd = code[0]
            if cmd == "M83":
                relative = True
            elif cmd == "M82":
                relative = False
            elif cmd == "G92":
                for tok in code[1:]:
                    if tok.startswith("E"):
                        e_pos = float(tok[1:])
            elif cmd in ("G0", "G1", "G2", "G3"):
                for tok in code[1:]:
                    if tok.startswith("E"):
                        val = float(tok[1:])
                        delta = val if relative else val - e_pos
                        if not relative:
                            e_pos = val
                        if z:
                            current += delta
    if z:
        per_layer.append(current)
    return GcodeInfo(path=path, comments=comments, config=config, layer_z=np.array(z),
                     layer_extrusion_mm=np.array(per_layer), generator=generator)
